export interface FlyerElemento {
  tipo: 'texto' | 'forma' | 'imagen'
  x: number
  y: number
  ancho?: number
  alto?: number
  texto?: string
  fuente?: string
  tamano?: number
  color?: string
  colorFondo?: string
  alineacion?: 'left' | 'center' | 'right'
  negrita?: boolean
  italica?: boolean
  opacidad?: number
  rx?: number // border radius for rectangles
  radio?: number // radius for circles
  forma?: 'rect' | 'circle'
}

export interface FlyerTemplate {
  id: string
  nombre: string
  categoria: 'reunion' | 'evento' | 'anuncio' | 'devocional' | 'especial' | 'social'
  ancho: number
  alto: number
  fondo: string // css gradient or hex
  fondoColores: string[] // used for canvas gradient
  elementos: FlyerElemento[]
  descripcion: string
}

export const FLYER_TEMPLATES: FlyerTemplate[] = [
  {
    id: 'reunion-red',
    nombre: 'Reunión de Red',
    categoria: 'reunion',
    ancho: 1080,
    alto: 1080,
    fondo: 'linear-gradient(135deg, #0f1629 0%, #1a2744 50%, #0f1629 100%)',
    fondoColores: ['#0f1629', '#1a2744', '#0f1629'],
    descripcion: 'Para convocar a la reunión mensual de la red',
    elementos: [
      {
        tipo: 'forma',
        forma: 'rect',
        x: 0,
        y: 0,
        ancho: 1080,
        alto: 1080,
        colorFondo: '#0f1629',
        opacidad: 1,
      },
      {
        tipo: 'forma',
        forma: 'rect',
        x: 60,
        y: 60,
        ancho: 960,
        alto: 960,
        colorFondo: 'transparent',
        color: '#c9a84c',
        opacidad: 0.4,
        rx: 16,
      },
      {
        tipo: 'forma',
        forma: 'rect',
        x: 80,
        y: 380,
        ancho: 920,
        alto: 8,
        colorFondo: '#c9a84c',
        opacidad: 0.7,
      },
      {
        tipo: 'forma',
        forma: 'rect',
        x: 80,
        y: 680,
        ancho: 920,
        alto: 8,
        colorFondo: '#c9a84c',
        opacidad: 0.7,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 160,
        texto: 'MINISTERIO DE CABALLEROS',
        fuente: 'Arial',
        tamano: 32,
        color: '#c9a84c',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.9,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 280,
        texto: 'REUNIÓN DE RED',
        fuente: 'Arial',
        tamano: 72,
        color: '#ffffff',
        alineacion: 'center',
        negrita: true,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 490,
        texto: 'RED MENOR · RED MEDIA · RED MAYOR',
        fuente: 'Arial',
        tamano: 28,
        color: '#c9a84c',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.9,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 590,
        texto: 'FECHA: [DÍA Y MES]',
        fuente: 'Arial',
        tamano: 44,
        color: '#ffffff',
        alineacion: 'center',
        negrita: true,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 770,
        texto: '⏰  HORA: 7:00 PM',
        fuente: 'Arial',
        tamano: 36,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 850,
        texto: '📍  LUGAR: [DIRECCIÓN]',
        fuente: 'Arial',
        tamano: 36,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 960,
        texto: 'TE ESPERAMOS · ¡NO FALTES!',
        fuente: 'Arial',
        tamano: 26,
        color: '#c9a84c',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.85,
      },
    ],
  },
  {
    id: 'culto-especial',
    nombre: 'Culto Especial',
    categoria: 'especial',
    ancho: 1080,
    alto: 1080,
    fondo: 'linear-gradient(160deg, #1a0533 0%, #3d0a6b 50%, #1a0533 100%)',
    fondoColores: ['#1a0533', '#3d0a6b', '#1a0533'],
    descripcion: 'Para anunciar cultos especiales con predicador invitado',
    elementos: [
      {
        tipo: 'forma',
        forma: 'rect',
        x: 0,
        y: 0,
        ancho: 1080,
        alto: 1080,
        colorFondo: '#1a0533',
        opacidad: 1,
      },
      {
        tipo: 'forma',
        forma: 'circle',
        x: 540,
        y: 300,
        radio: 220,
        colorFondo: '#3d0a6b',
        opacidad: 0.5,
      },
      {
        tipo: 'forma',
        forma: 'rect',
        x: 100,
        y: 500,
        ancho: 880,
        alto: 6,
        colorFondo: '#d4af37',
        opacidad: 0.9,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 120,
        texto: '✝  MINISTERIO GEDEONES',
        fuente: 'Arial',
        tamano: 30,
        color: '#d4af37',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.9,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 270,
        texto: 'CULTO',
        fuente: 'Arial',
        tamano: 96,
        color: '#ffffff',
        alineacion: 'center',
        negrita: true,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 390,
        texto: 'ESPECIAL',
        fuente: 'Arial',
        tamano: 96,
        color: '#d4af37',
        alineacion: 'center',
        negrita: true,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 570,
        texto: 'PREDICADOR INVITADO',
        fuente: 'Arial',
        tamano: 28,
        color: '#d4af37',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.8,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 660,
        texto: '[NOMBRE DEL PREDICADOR]',
        fuente: 'Arial',
        tamano: 52,
        color: '#ffffff',
        alineacion: 'center',
        negrita: true,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 780,
        texto: '[FECHA] · [HORA]',
        fuente: 'Arial',
        tamano: 38,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 880,
        texto: '[NOMBRE DEL TEMPLO]',
        fuente: 'Arial',
        tamano: 32,
        color: '#d4af37',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.9,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 980,
        texto: '¡TODOS ESTÁN INVITADOS!',
        fuente: 'Arial',
        tamano: 24,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.7,
      },
    ],
  },
  {
    id: 'retiro-caballeros',
    nombre: 'Retiro de Caballeros',
    categoria: 'evento',
    ancho: 1080,
    alto: 1080,
    fondo: 'linear-gradient(160deg, #0b1f0b 0%, #1a3a1a 50%, #0b1f0b 100%)',
    fondoColores: ['#0b1f0b', '#1a3a1a', '#0b1f0b'],
    descripcion: 'Para convocar al retiro anual de caballeros',
    elementos: [
      {
        tipo: 'forma',
        forma: 'rect',
        x: 0,
        y: 0,
        ancho: 1080,
        alto: 1080,
        colorFondo: '#0b1f0b',
        opacidad: 1,
      },
      {
        tipo: 'forma',
        forma: 'rect',
        x: 0,
        y: 600,
        ancho: 1080,
        alto: 480,
        colorFondo: '#1a3a1a',
        opacidad: 0.6,
      },
      {
        tipo: 'forma',
        forma: 'rect',
        x: 80,
        y: 480,
        ancho: 920,
        alto: 6,
        colorFondo: '#7ec850',
        opacidad: 0.8,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 120,
        texto: 'MINISTERIO DE CABALLEROS',
        fuente: 'Arial',
        tamano: 30,
        color: '#7ec850',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.9,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 230,
        texto: 'RETIRO',
        fuente: 'Arial',
        tamano: 110,
        color: '#ffffff',
        alineacion: 'center',
        negrita: true,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 370,
        texto: 'DE CABALLEROS',
        fuente: 'Arial',
        tamano: 58,
        color: '#7ec850',
        alineacion: 'center',
        negrita: true,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 560,
        texto: '"HOMBRES DE FE"',
        fuente: 'Arial',
        tamano: 40,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        italica: true,
        opacidad: 0.85,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 680,
        texto: '📅  [FECHA DE INICIO] AL [FECHA FIN]',
        fuente: 'Arial',
        tamano: 34,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 770,
        texto: '📍  [LUGAR DEL RETIRO]',
        fuente: 'Arial',
        tamano: 34,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 870,
        texto: 'Inscripciones: [CONTACTO]',
        fuente: 'Arial',
        tamano: 28,
        color: '#7ec850',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.9,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 970,
        texto: '¡TRANSFORMA TU VIDA!',
        fuente: 'Arial',
        tamano: 26,
        color: '#ffffff',
        alineacion: 'center',
        negrita: true,
        opacidad: 0.7,
      },
    ],
  },
  {
    id: 'devocional-semanal',
    nombre: 'Devocional Semanal',
    categoria: 'devocional',
    ancho: 1080,
    alto: 1080,
    fondo: 'linear-gradient(160deg, #1c1410 0%, #2d2015 50%, #1c1410 100%)',
    fondoColores: ['#1c1410', '#2d2015', '#1c1410'],
    descripcion: 'Para compartir el devocional y versículo semanal',
    elementos: [
      {
        tipo: 'forma',
        forma: 'rect',
        x: 0,
        y: 0,
        ancho: 1080,
        alto: 1080,
        colorFondo: '#1c1410',
        opacidad: 1,
      },
      {
        tipo: 'forma',
        forma: 'rect',
        x: 120,
        y: 120,
        ancho: 840,
        alto: 840,
        colorFondo: '#2d2015',
        opacidad: 0.5,
        rx: 24,
      },
      {
        tipo: 'forma',
        forma: 'rect',
        x: 200,
        y: 200,
        ancho: 680,
        alto: 4,
        colorFondo: '#e8c56a',
        opacidad: 0.6,
      },
      {
        tipo: 'forma',
        forma: 'rect',
        x: 200,
        y: 880,
        ancho: 680,
        alto: 4,
        colorFondo: '#e8c56a',
        opacidad: 0.6,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 175,
        texto: '✦  DEVOCIONAL SEMANAL  ✦',
        fuente: 'Arial',
        tamano: 26,
        color: '#e8c56a',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.9,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 320,
        texto: '"[VERSÍCULO BÍBLICO]',
        fuente: 'Arial',
        tamano: 42,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        italica: true,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 460,
        texto: '[CONTINUACIÓN DEL VERSÍCULO]"',
        fuente: 'Arial',
        tamano: 42,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        italica: true,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 570,
        texto: '— [LIBRO CAPÍTULO:VERSÍCULO]',
        fuente: 'Arial',
        tamano: 30,
        color: '#e8c56a',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.9,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 690,
        texto: '[REFLEXIÓN O ENSEÑANZA BREVE]',
        fuente: 'Arial',
        tamano: 32,
        color: '#c8b89a',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.85,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 800,
        texto: '[SEMANA DEL: FECHA]',
        fuente: 'Arial',
        tamano: 26,
        color: '#e8c56a',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.75,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 910,
        texto: 'MINISTERIO DE CABALLEROS GEDEONES',
        fuente: 'Arial',
        tamano: 22,
        color: '#c8b89a',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.65,
      },
    ],
  },
  {
    id: 'anuncio-general',
    nombre: 'Anuncio General',
    categoria: 'anuncio',
    ancho: 1080,
    alto: 1080,
    fondo: 'linear-gradient(135deg, #0d1117 0%, #161b22 100%)',
    fondoColores: ['#0d1117', '#161b22'],
    descripcion: 'Plantilla limpia y moderna para cualquier anuncio',
    elementos: [
      {
        tipo: 'forma',
        forma: 'rect',
        x: 0,
        y: 0,
        ancho: 1080,
        alto: 1080,
        colorFondo: '#0d1117',
        opacidad: 1,
      },
      {
        tipo: 'forma',
        forma: 'rect',
        x: 0,
        y: 0,
        ancho: 12,
        alto: 1080,
        colorFondo: '#3b82f6',
        opacidad: 1,
      },
      {
        tipo: 'forma',
        forma: 'rect',
        x: 80,
        y: 200,
        ancho: 800,
        alto: 6,
        colorFondo: '#3b82f6',
        opacidad: 0.7,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 120,
        texto: 'MINISTERIO DE CABALLEROS',
        fuente: 'Arial',
        tamano: 28,
        color: '#3b82f6',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.9,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 310,
        texto: '📢  ANUNCIO',
        fuente: 'Arial',
        tamano: 56,
        color: '#ffffff',
        alineacion: 'center',
        negrita: true,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 450,
        texto: '[TÍTULO DEL ANUNCIO]',
        fuente: 'Arial',
        tamano: 64,
        color: '#3b82f6',
        alineacion: 'center',
        negrita: true,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 600,
        texto: '[DESCRIPCIÓN O DETALLE IMPORTANTE',
        fuente: 'Arial',
        tamano: 36,
        color: '#94a3b8',
        alineacion: 'center',
        negrita: false,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 660,
        texto: 'del anuncio que desea comunicar]',
        fuente: 'Arial',
        tamano: 36,
        color: '#94a3b8',
        alineacion: 'center',
        negrita: false,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 790,
        texto: '[FECHA · HORA · LUGAR]',
        fuente: 'Arial',
        tamano: 38,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 920,
        texto: 'Para más información: [CONTACTO]',
        fuente: 'Arial',
        tamano: 28,
        color: '#64748b',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.9,
      },
    ],
  },
  {
    id: 'evento-social',
    nombre: 'Evento Social',
    categoria: 'social',
    ancho: 1080,
    alto: 1080,
    fondo: 'linear-gradient(135deg, #1a0a00 0%, #2d1500 50%, #1a0a00 100%)',
    fondoColores: ['#1a0a00', '#2d1500', '#1a0a00'],
    descripcion: 'Para eventos de confraternidad y actividades sociales',
    elementos: [
      {
        tipo: 'forma',
        forma: 'rect',
        x: 0,
        y: 0,
        ancho: 1080,
        alto: 1080,
        colorFondo: '#1a0a00',
        opacidad: 1,
      },
      {
        tipo: 'forma',
        forma: 'circle',
        x: 540,
        y: 480,
        radio: 380,
        colorFondo: '#ff6b35',
        opacidad: 0.1,
      },
      {
        tipo: 'forma',
        forma: 'rect',
        x: 80,
        y: 560,
        ancho: 920,
        alto: 5,
        colorFondo: '#ff6b35',
        opacidad: 0.6,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 120,
        texto: '🎉  MINISTERIO DE CABALLEROS',
        fuente: 'Arial',
        tamano: 28,
        color: '#ff6b35',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.9,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 260,
        texto: 'EVENTO DE',
        fuente: 'Arial',
        tamano: 72,
        color: '#ffffff',
        alineacion: 'center',
        negrita: true,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 390,
        texto: 'CONFRATERNIDAD',
        fuente: 'Arial',
        tamano: 60,
        color: '#ff6b35',
        alineacion: 'center',
        negrita: true,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 490,
        texto: '[NOMBRE DEL EVENTO]',
        fuente: 'Arial',
        tamano: 44,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        italica: true,
        opacidad: 0.85,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 650,
        texto: '📅  [FECHA]',
        fuente: 'Arial',
        tamano: 40,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 740,
        texto: '⏰  [HORA]',
        fuente: 'Arial',
        tamano: 40,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 840,
        texto: '📍  [LUGAR]',
        fuente: 'Arial',
        tamano: 40,
        color: '#ffffff',
        alineacion: 'center',
        negrita: false,
        opacidad: 1,
      },
      {
        tipo: 'texto',
        x: 540,
        y: 960,
        texto: '¡FAMILIAS BIENVENIDAS!  🙌',
        fuente: 'Arial',
        tamano: 30,
        color: '#ff6b35',
        alineacion: 'center',
        negrita: false,
        opacidad: 0.9,
      },
    ],
  },
]

export const getCategoriaLabel = (cat: FlyerTemplate['categoria']): string => {
  const labels: Record<string, string> = {
    reunion: 'Reunión',
    evento: 'Evento',
    anuncio: 'Anuncio',
    devocional: 'Devocional',
    especial: 'Especial',
    social: 'Social',
  }
  return labels[cat] ?? cat
}
